ObjectsBucket:
  Type: AWS::S3::Bucket
  Properties:
    AccessControl: Private
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
            KMSMasterKeyID: ${env:S3_OBJECT_BUCKET_KMS_KEY_ARN}
    BucketName: ${env:S3_OBJECTS_BUCKET_NAME}
    PublicAccessBlockConfiguration:
      BlockPublicAcls : true
      BlockPublicPolicy : true
      IgnorePublicAcls : true
      RestrictPublicBuckets : true
