ObjectsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${env:DYNAMODB_OBJECTS_TABLE_NAME}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH